# Site
name: 'Machine Learning Club'
description: 'A Community of Self-Taught ML Enthusiasts.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/MLClub'
disqus: 'machine-learning-club'
email: 'g.himanshu2312@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    himanshu:
      name:           Himanshu
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar_him.jpg
      bio:            "Hi, I am Himanshu, author of ML Club. I hope you like it!"
      email:          g.himanshu2312@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Himanshu
      avatar: /assets/images/avatar_him.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]